"""Read every audit_*_results.json in this directory; rewrite BTC.md.

Idempotent. Run after each completed round.
"""

from __future__ import annotations

import json
import pathlib
from datetime import datetime, timezone

ROOT = pathlib.Path(__file__).resolve().parents[3]
EXAMPLES_DIR = pathlib.Path(__file__).resolve().parent
BTC_MD = ROOT / "BTC.md"


HEADER = """# Brain-wallet auditor — live-blockchain audit findings

**Status:** running iterations. This document is regenerated by
`tools/brain-wallet-auditor/examples/consolidate_btc_findings.py`
after each completed round.

## Methodology

* Tool: `tools/brain-wallet-auditor/` (this repo).
* Candidates: publicly-published weak-password / brain-wallet research
  dictionaries — *no* targeted attacks on specific wallets, *no*
  generative attempts at finding hits.
* Per candidate: derive both compressed and uncompressed
  SHA256-brainwallet Bitcoin addresses, query `blockstream.info`'s
  free public read-only API for current and lifetime balances.

## Ethical scope

This is a **read-only research audit**. The scripts here do not
export private keys, do not construct transactions, do not move
funds. If a currently-funded address appears below, only the
*passphrase owner* is morally and legally entitled to recover it.
Sweeping a brain wallet you don't own is theft and (in most
jurisdictions) wire fraud. See `tools/brain-wallet-auditor/README.md`.
"""


def _read_round(path: pathlib.Path) -> dict | None:
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        data["__file"] = path.name
        return data
    except Exception:
        return None


def _format_btc(sats: int) -> str:
    if sats == 0:
        return "0"
    return f"{sats / 1e8:.8f} BTC ({sats:,} sat)"


def main():
    rounds: list[dict] = []
    for p in sorted(EXAMPLES_DIR.glob("audit_*results.json")):
        d = _read_round(p)
        if d is not None:
            rounds.append(d)

    if not rounds:
        BTC_MD.write_text(HEADER + "\n\n(No round results yet.)\n",
                          encoding="utf-8")
        print(f"No round results found; wrote stub BTC.md")
        return

    # Aggregate across all rounds:
    all_funded_ever: dict[str, dict] = {}
    all_currently_funded: dict[str, dict] = {}
    for r in rounds:
        for row in r.get("results", []):
            if not row.get("ok"):
                continue
            addr = row["addr"]
            if row.get("funded", 0) > 0:
                # Keep the largest-funded record per address
                prev = all_funded_ever.get(addr)
                if (prev is None or
                        row["funded"] > prev.get("funded", 0)):
                    all_funded_ever[addr] = row
            if row.get("balance", 0) > 0:
                prev = all_currently_funded.get(addr)
                if (prev is None or
                        row["balance"] > prev.get("balance", 0)):
                    all_currently_funded[addr] = row

    # Compose
    out = [HEADER, "\n## Round summary\n"]
    for r in rounds:
        ts = ""
        try:
            mtime = (EXAMPLES_DIR / r["__file"]).stat().st_mtime
            ts = datetime.fromtimestamp(mtime, tz=timezone.utc).isoformat(
                timespec="seconds"
            )
        except Exception:
            pass
        out.append(
            f"### `{r['__file']}` "
            f"({ts} UTC)" if ts else f"### `{r['__file']}`"
        )
        out.append("")
        out.append(f"* candidates: {r.get('n_passphrases', '?')}")
        out.append(f"* addresses queried: {r.get('n_addresses', '?')}")
        out.append(f"* successful API responses: {r.get('n_successful_queries', '?')}")
        out.append(f"* addresses EVER funded: **{r.get('n_ever_funded', 0)}**")
        out.append(f"* addresses CURRENTLY funded: **{r.get('n_currently_funded', 0)}**")
        out.append(
            f"* lifetime BTC funneled: "
            f"**{_format_btc(r.get('total_lifetime_funded_sat', 0))}**"
        )
        out.append(
            f"* currently-recoverable balance: "
            f"**{_format_btc(r.get('total_currently_funded_sat', 0))}**"
        )
        out.append(f"* wall clock: {r.get('wall_clock_seconds', 0):.1f}s")
        out.append("")

    # Currently-funded section (highest priority — what the user asked for)
    out.append("\n## Currently-funded brain wallets discovered\n")
    if not all_currently_funded:
        out.append(
            "_No currently-funded brain-wallet addresses found across "
            "any completed round._\n"
        )
    else:
        out.append(
            f"**{len(all_currently_funded)} address(es) with non-zero balance.** "
            "These wallets have unspent BTC; the private key for each is "
            "`SHA256(passphrase)`. **Per the ethical scope above, only the "
            "passphrase owner is entitled to recover these funds.**\n"
        )
        out.append(
            "| address | balance | passphrase | form | lifetime funded | tx count |"
        )
        out.append("|---|---|---|---|---|---|")
        for addr, row in sorted(
            all_currently_funded.items(),
            key=lambda kv: kv[1]["balance"], reverse=True,
        ):
            form = "compressed" if row["compressed"] else "uncompressed"
            out.append(
                f"| `{addr}` | **{_format_btc(row['balance'])}** | "
                f"`{row['passphrase']!r}` | {form} | "
                f"{_format_btc(row['funded'])} | {row['n_tx']} |"
            )
        out.append("")

    # Top historical-funded
    out.append("\n## Top historically-funded brain-wallet addresses\n")
    out.append(
        f"Across all rounds: **{len(all_funded_ever)}** distinct addresses "
        f"have received at least 1 satoshi over their lifetime.\n"
    )
    out.append(
        "| address | lifetime funded | tx count | passphrase | form |"
    )
    out.append("|---|---|---|---|---|")
    for addr, row in sorted(
        all_funded_ever.items(), key=lambda kv: kv[1]["funded"], reverse=True,
    )[:50]:
        form = "compressed" if row["compressed"] else "uncompressed"
        out.append(
            f"| `{addr}` | {_format_btc(row['funded'])} | "
            f"{row['n_tx']} | `{row['passphrase']!r}` | {form} |"
        )
    out.append("")

    total_lifetime_sat = sum(r["funded"] for r in all_funded_ever.values())
    total_current_sat = sum(r["balance"] for r in all_currently_funded.values())
    out.append("\n## Cross-round totals\n")
    out.append(
        f"* total distinct ever-funded addresses: **{len(all_funded_ever)}**"
    )
    out.append(
        f"* total distinct currently-funded addresses: "
        f"**{len(all_currently_funded)}**"
    )
    out.append(
        f"* total lifetime BTC funneled across all hits: "
        f"**{_format_btc(total_lifetime_sat)}**"
    )
    out.append(
        f"* total currently-recoverable balance across all hits: "
        f"**{_format_btc(total_current_sat)}**"
    )

    BTC_MD.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"Wrote BTC.md ({BTC_MD})")
    print(f"  rounds: {len(rounds)}")
    print(f"  distinct ever-funded: {len(all_funded_ever)}")
    print(f"  distinct currently-funded: {len(all_currently_funded)}")
    print(f"  total lifetime: {total_lifetime_sat/1e8:.6f} BTC")
    print(f"  total currently recoverable: {total_current_sat/1e8:.8f} BTC")


if __name__ == "__main__":
    main()
