"""Magnetic monopole on a rotating LP cylinder.

A magnetic monopole of charge g sitting at the axis of a rotating
cylinder couples to the electric field generated by the rotating
charge distribution (if the cylinder carries any charge density).
In the LP framework, the gravitational analog is the coupling between
a "gravitomagnetic monopole" (NUT charge) and the frame-dragging
field K(r) of the cylinder.

Dirac quantization: g e = 2 pi n hbar / 2.
For our analog: g_grav * a = pi n.
This gives discrete allowed monopole charges given the cylinder's
rotation parameter a = omega R.

Module:
- dirac_quantization_condition: allowed monopole charges
- monopole_field_at_r: B-field profile (or NUT analog)
- monopole_cylinder_interaction_energy
- novelty_scan: catcher on allowed-charge spectrum vs a
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np

from systrophe.catchers.novelty_catcher import scan_novelty
from systrophe.geometry.vanstockum import VanStockumInterior


@dataclass(frozen=True)
class MonopoleConfig:
    n_dirac_quantum: int
    g_charge: float
    interaction_energy: float


def dirac_quantization_condition(
    vs: VanStockumInterior, n_max: int = 5,
) -> list[float]:
    """Allowed monopole charges g_n satisfying g_n * a = pi n."""
    a = vs.a
    if a <= 0:
        return []
    return [float(math.pi * n / a) for n in range(1, n_max + 1)]


def monopole_field_at_r(r: float, g_charge: float = 1.0) -> float:
    """Magnetic field magnitude B(r) = g / (4 pi r^2)."""
    if r <= 0:
        return float("inf")
    return float(g_charge / (4 * math.pi * r ** 2))


def monopole_cylinder_interaction_energy(
    vs: VanStockumInterior, g_charge: float = 1.0,
    r_separation: float = 2.0,
) -> float:
    """Heuristic interaction: U ~ g * (rotation flux) / r."""
    a = vs.a
    flux = a * math.pi * vs.R ** 2  # rough rotation flux
    U = g_charge * flux / max(r_separation, 1e-12)
    return float(U)


def NUT_charge_analog(vs: VanStockumInterior) -> float:
    """Gravitomagnetic NUT charge analog from K(R) at the cylinder."""
    K_R = float(vs.analytic_exterior_K(np.array([vs.R * 1.001]))[0])
    return float(K_R)


def witten_effect(
    vs: VanStockumInterior, theta_angle: float = 0.0,
    n_dirac: int = 1,
) -> dict:
    """Witten effect: theta-angle shifts monopole electric charge.

    For our analog: gravitomagnetic monopole acquires effective angular
    momentum L_eff = n_dirac * theta_angle / (2 pi).
    """
    L_eff = n_dirac * theta_angle / (2 * math.pi)
    return {
        "theta_angle": theta_angle,
        "n_dirac": n_dirac,
        "effective_angular_momentum": float(L_eff),
    }


def novelty_scan(n_a_values: int = 30) -> dict:
    """Catcher: scan over a = omega*R, look at allowed-charge spectrum."""
    a_grid = np.linspace(0.6, 5.0, n_a_values)
    def fn(a_float: float) -> np.ndarray:
        vs = VanStockumInterior(omega=a_float, R=1.0)
        charges = dirac_quantization_condition(vs, n_max=5)
        return np.array(charges)
    result = scan_novelty(a_grid, fn, n_bits=32, parameter_label="a")
    return {
        "verdict": result.verdict,
        "n_sharp_features": len(result.sharp_features),
        "sharp_features": result.sharp_features,
        "lambda_2_at_radius": result.lambda_2_at_radius,
    }
